services:
  hytale:
    image: ghcr.io/visualies/hytale-server:latest
    environment:
      HYTALE_OWNER_UUID: ${HYTALE_OWNER_UUID:-}
    volumes:
      - ./server-data:/data
    ports:
      - "5520:5520/udp"
    restart: unless-stopped
