services:
  hytale:
    image: ghcr.io/visualies/hytale-server:latest
    environment:
      HYTALE_OWNER_UUID: ${HYTALE_OWNER_UUID:-}
      JAVA_OPTS: ${JAVA_OPTS:--XX:AOTCache=/data/Server/HytaleServer.aot -Xms4g -Xmx8g}
    volumes:
      - ./server-data:/data
    ports:
      - "5520:5520/udp"
    restart: unless-stopped
