services:
  hytale:
    image: ghcr.io/visualies/hytale-server:latest
    environment:
      MAX_MEMORY: 8G
    volumes:
      - ./server-data:/data
    ports:
      - "5520:5520/udp"
    restart: unless-stopped